
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox2;
	
	private global::Gtk.Label mainWindowTitleLabel;
	
	private global::Gtk.HBox hbox3;
	
	private global::Gtk.VBox vbox3;
	
	private global::Gtk.Label Test_Senario_Lable;
	
	private global::Gtk.ComboBox testSenarioComboBox;
	
	private global::Gtk.HBox hbox4;
	
	private global::Gtk.Button New_Senario_Create_Button;
	
	private global::Gtk.Button startTestButton;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(3));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.mainWindowTitleLabel = new global::Gtk.Label ();
		this.mainWindowTitleLabel.Name = "mainWindowTitleLabel";
		this.mainWindowTitleLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Sim Harnes");
		this.mainWindowTitleLabel.Justify = ((global::Gtk.Justification)(2));
		this.vbox2.Add (this.mainWindowTitleLabel);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.mainWindowTitleLabel]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.Test_Senario_Lable = new global::Gtk.Label ();
		this.Test_Senario_Lable.Name = "Test_Senario_Lable";
		this.Test_Senario_Lable.LabelProp = global::Mono.Unix.Catalog.GetString ("Test Senarios");
		this.vbox3.Add (this.Test_Senario_Lable);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.Test_Senario_Lable]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.testSenarioComboBox = global::Gtk.ComboBox.NewText ();
		this.testSenarioComboBox.Name = "testSenarioComboBox";
		this.vbox3.Add (this.testSenarioComboBox);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.testSenarioComboBox]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		this.hbox3.Add (this.vbox3);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.vbox3]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		this.vbox2.Add (this.hbox3);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox3]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.New_Senario_Create_Button = new global::Gtk.Button ();
		this.New_Senario_Create_Button.CanFocus = true;
		this.New_Senario_Create_Button.Name = "New_Senario_Create_Button";
		this.New_Senario_Create_Button.UseUnderline = true;
		this.New_Senario_Create_Button.Label = global::Mono.Unix.Catalog.GetString ("New Senario");
		this.hbox4.Add (this.New_Senario_Create_Button);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.New_Senario_Create_Button]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.startTestButton = new global::Gtk.Button ();
		this.startTestButton.CanFocus = true;
		this.startTestButton.Name = "startTestButton";
		this.startTestButton.UseUnderline = true;
		this.startTestButton.Label = global::Mono.Unix.Catalog.GetString ("Start Test");
		this.hbox4.Add (this.startTestButton);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.startTestButton]));
		w7.Position = 2;
		w7.Expand = false;
		w7.Fill = false;
		this.vbox2.Add (this.hbox4);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox4]));
		w8.Position = 2;
		w8.Expand = false;
		w8.Fill = false;
		this.Add (this.vbox2);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 139;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.New_Senario_Create_Button.Clicked += new global::System.EventHandler (this.OnNewSenarioCreateButtonClicked);
		this.startTestButton.Clicked += new global::System.EventHandler (this.OnStartTestButtonClicked);
	}
}
